// TAB SWITCHING
const tabButtons = document.querySelectorAll(".tab-btn");
const tabContents = document.querySelectorAll(".tab-content");

tabButtons.forEach(btn => {
    btn.addEventListener("click", () => {
        tabButtons.forEach(b => b.classList.remove("active"));
        tabContents.forEach(c => c.classList.remove("active"));

        btn.classList.add("active");
        document.getElementById(btn.dataset.tab + "-tab")
            .classList.add("active");
    });
});

// RESUME FORM SUBMIT
document.getElementById("resume-form")?.addEventListener("submit", e => {
    e.preventDefault();
    showLoader();

    setTimeout(() => {
        document.getElementById("resume-content").innerHTML = `
            <h2>Your AI Generated Resume</h2>
            <p>This is a sample resume generated by AI.</p>
        `;
        hideLoader();
    }, 2000);
});

// LOADER
function showLoader() {
    document.getElementById("loading-overlay").style.display = "flex";
}

function hideLoader() {
    document.getElementById("loading-overlay").style.display = "none";
}
